# Feature Extraction from Human Observed Raw Data

In [1]:
import pandas as pd

In [8]:
same_diff_pair = pd.read_csv('same_diff_pairs.csv')

In [9]:
same_diff_pair.head()

  img_id_A img_id_B
0    0359a    0359b
1    0577a    0577b
2    0577a    0577c
3    1120a    1120b
4    1120a    1120c

In [10]:
same_diff_pair.columns

Index(['img_id_A', 'img_id_B'], dtype='object')

In [11]:
same_diff_pair.tail()

       img_id_A img_id_B
293818    1125b    1224b
293819    1125b    0302b
293820    0416a    1224b
293821    0416a    0302b
293822    1224b    0302b

In [12]:
feature_list = pd.read_csv('HumanObserved-Features-Data.csv',index_col='id')

In [13]:
feature_list.head()

   img_id  f1  f2  f3  f4  f5  f6  f7  f8  f9
id
0   0359a   2   1   1   0   2   2   0   2   2
1   0577a   2   1   1   0   2   2   0   1   2
2   1120a   2   1   1   3   2   2   0   2   2
3   1120b   1   1   1   0   2   2   0   2   2
4   1120c   2   1   1   0   2   2   0   0   2

In [14]:
temp = same_diff_pair.merge(feature_list, how='inner', left_on='img_id_A', right_on='img_id')
temp = temp.drop(columns=['img_id'])
temp.head(2)

  img_id_A img_id_B  f1  f2  f3  f4  f5  f6  f7  f8  f9
0    0359a    0359b   2   1   1   0   2   2   0   2   2
1    0359a    0577a   2   1   1   0   2   2   0   2   2

In [15]:
merged_df = temp.merge(feature_list, how='inner', left_on='img_id_B', right_on='img_id')
merged_df = merged_df.drop(columns=['img_id'])
merged_df.head(2)

,img_id_A,img_id_B,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,f8_x,f9_x,f1_y,f2_y,f3_y,f4_y,f5_y,f6_y,f7_y,f8_y,f9_y
0,0359a,0359b,2,1,1,0,2,2,0,2,2,3,2,1,0,2,2,3,0,2
1,1468a,0359b,1,1,1,2,2,2,0,0,2,3,2,1,0,2,2,3,0,2

In [16]:
merged_df.tail()

,img_id_A,img_id_B,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,f8_x,f9_x,f1_y,f2_y,f3_y,f4_y,f5_y,f6_y,f7_y,f8_y,f9_y
293818,0380b,0302b,1,3,2,3,3,2,0,2,2,2,2,2,4,3,3,3,4,2
293819,1083a,0302b,0,4,2,4,2,3,1,1,1,2,2,2,4,3,3,3,4,2
293820,1125b,0302b,1,1,2,4,3,2,1,2,1,2,2,2,4,3,3,3,4,2
293821,0416a,0302b,1,1,2,4,3,2,1,1,1,2,2,2,4,3,3,3,4,2
293822,1224b,0302b,2,4,2,4,3,3,3,4,2,2,2,2,4,3,3,3,4,2

In [17]:
merged_df.head()

,img_id_A,img_id_B,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,f8_x,f9_x,f1_y,f2_y,f3_y,f4_y,f5_y,f6_y,f7_y,f8_y,f9_y
0,0359a,0359b,2,1,1,0,2,2,0,2,2,3,2,1,0,2,2,3,0,2
1,1468a,0359b,1,1,1,2,2,2,0,0,2,3,2,1,0,2,2,3,0,2
2,1483a,0359b,2,1,1,3,2,3,0,3,2,3,2,1,0,2,2,3,0,2
3,1488a,0359b,1,1,1,0,2,3,0,0,2,3,2,1,0,2,2,3,0,2
4,1534c,0359b,3,1,1,0,2,1,0,3,2,3,2,1,0,2,2,3,0,2

In [23]:
merged_df.head()

,img_id_A,img_id_B,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,f8_x,f9_x,f1_y,f2_y,f3_y,f4_y,f5_y,f6_y,f7_y,f8_y,f9_y
0,0359a,0359b,2,1,1,0,2,2,0,2,2,3,2,1,0,2,2,3,0,2
1,1468a,0359b,1,1,1,2,2,2,0,0,2,3,2,1,0,2,2,3,0,2
2,1483a,0359b,2,1,1,3,2,3,0,3,2,3,2,1,0,2,2,3,0,2
3,1488a,0359b,1,1,1,0,2,3,0,0,2,3,2,1,0,2,2,3,0,2
4,1534c,0359b,3,1,1,0,2,1,0,3,2,3,2,1,0,2,2,3,0,2

In [26]:
merged_df.to_csv('Same_Diff_Feature_Concat.csv')

In [27]:
merged_df = merged_df.drop(columns=['img_id_A','img_id_B'])

In [28]:
merged_df.head()

,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,f8_x,f9_x,f1_y,f2_y,f3_y,f4_y,f5_y,f6_y,f7_y,f8_y,f9_y
0,2,1,1,0,2,2,0,2,2,3,2,1,0,2,2,3,0,2
1,1,1,1,2,2,2,0,0,2,3,2,1,0,2,2,3,0,2
2,2,1,1,3,2,3,0,3,2,3,2,1,0,2,2,3,0,2
3,1,1,1,0,2,3,0,0,2,3,2,1,0,2,2,3,0,2
4,3,1,1,0,2,1,0,3,2,3,2,1,0,2,2,3,0,2

In [29]:
merged_df.to_csv('Same_Diff_Feature_Concat_withoutlabel_raw.csv')
#Index labels removed manually to make a matrix.

In [31]:
Same_Diff_merged_df = pd.read_csv('Same_Diff_Feature_Concat_withoutlabel.csv')

In [33]:
merged_subtract_df = pd.read_csv('Same_Diff_Feature_Concat.csv')

In [34]:
merged_subtract_df.head()

,Unnamed: 0,img_id_A,img_id_B,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,...,f9_x,f1_y,f2_y,f3_y,f4_y,f5_y,f6_y,f7_y,f8_y,f9_y
0,0,0359a,0359b,2,1,1,0,2,2,0,...,2,3,2,1,0,2,2,3,0,2
1,1,1468a,0359b,1,1,1,2,2,2,0,...,2,3,2,1,0,2,2,3,0,2
2,2,1483a,0359b,2,1,1,3,2,3,0,...,2,3,2,1,0,2,2,3,0,2
3,3,1488a,0359b,1,1,1,0,2,3,0,...,2,3,2,1,0,2,2,3,0,2
4,4,1534c,0359b,3,1,1,0,2,1,0,...,2,3,2,1,0,2,2,3,0,2

In [35]:
merged_subtract_df = merged_subtract_df.drop(columns=['Unnamed: 0'])

In [36]:
merged_subtract_df.head()

,img_id_A,img_id_B,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,f8_x,f9_x,f1_y,f2_y,f3_y,f4_y,f5_y,f6_y,f7_y,f8_y,f9_y
0,0359a,0359b,2,1,1,0,2,2,0,2,2,3,2,1,0,2,2,3,0,2
1,1468a,0359b,1,1,1,2,2,2,0,0,2,3,2,1,0,2,2,3,0,2
2,1483a,0359b,2,1,1,3,2,3,0,3,2,3,2,1,0,2,2,3,0,2
3,1488a,0359b,1,1,1,0,2,3,0,0,2,3,2,1,0,2,2,3,0,2
4,1534c,0359b,3,1,1,0,2,1,0,3,2,3,2,1,0,2,2,3,0,2

In [38]:
merged_subtract_df['f1_x'] = abs(merged_subtract_df['f1_x'] - merged_subtract_df['f1_y'])
merged_subtract_df['f2_x'] = abs(merged_subtract_df['f2_x'] - merged_subtract_df['f2_y'])
merged_subtract_df['f3_x'] = abs(merged_subtract_df['f3_x'] - merged_subtract_df['f3_y'])
merged_subtract_df['f4_x'] = abs(merged_subtract_df['f4_x'] - merged_subtract_df['f4_y'])
merged_subtract_df['f5_x'] = abs(merged_subtract_df['f5_x'] - merged_subtract_df['f5_y'])
merged_subtract_df['f6_x'] = abs(merged_subtract_df['f6_x'] - merged_subtract_df['f6_y'])
merged_subtract_df['f7_x'] = abs(merged_subtract_df['f7_x'] - merged_subtract_df['f7_y'])
merged_subtract_df['f8_x'] = abs(merged_subtract_df['f8_x'] - merged_subtract_df['f8_y'])
merged_subtract_df['f9_x'] = abs(merged_subtract_df['f9_x'] - merged_subtract_df['f9_y'])

In [39]:
merged_subtract_df.head()

,img_id_A,img_id_B,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,f8_x,f9_x,f1_y,f2_y,f3_y,f4_y,f5_y,f6_y,f7_y,f8_y,f9_y
0,0359a,0359b,2,1,0,0,0,0,3,2,0,3,2,1,0,2,2,3,0,2
1,1468a,0359b,1,1,0,2,0,0,3,0,0,3,2,1,0,2,2,3,0,2
2,1483a,0359b,2,1,0,3,0,1,3,3,0,3,2,1,0,2,2,3,0,2
3,1488a,0359b,1,1,0,0,0,1,3,0,0,3,2,1,0,2,2,3,0,2
4,1534c,0359b,3,1,0,0,0,1,3,3,0,3,2,1,0,2,2,3,0,2

In [40]:
merged_subtract_df = merged_subtract_df.drop(columns=['f1_y','f2_y','f3_y','f4_y','f5_y','f6_y','f7_y','f8_y','f9_y'])

In [41]:
merged_subtract_df.head()

  img_id_A img_id_B  f1_x  f2_x  f3_x  f4_x  f5_x  f6_x  f7_x  f8_x  f9_x
0    0359a    0359b     2     1     0     0     0     0     3     2     0
1    1468a    0359b     1     1     0     2     0     0     3     0     0
2    1483a    0359b     2     1     0     3     0     1     3     3     0
3    1488a    0359b     1     1     0     0     0     1     3     0     0
4    1534c    0359b     3     1     0     0     0     1     3     3     0

In [42]:
merged_subtract_df.to_csv('Same_Diff_Feature_Subtract.csv')

In [43]:
merged_subtract_df = merged_subtract_df.drop(columns=['img_id_A','img_id_B'])

In [44]:
merged_subtract_df.head()

   f1_x  f2_x  f3_x  f4_x  f5_x  f6_x  f7_x  f8_x  f9_x
0     2     1     0     0     0     0     3     2     0
1     1     1     0     2     0     0     3     0     0
2     2     1     0     3     0     1     3     3     0
3     1     1     0     0     0     1     3     0     0
4     3     1     0     0     0     1     3     3     0

In [45]:
merged_subtract_df.to_csv('Same_Diff_Feature_Subtract_withoutlabel_raw.csv')

In [46]:
msd = pd.read_csv('Same_Diff_Feature_Subtract_withoutlabel.csv')

In [2]:
from sklearn.cluster import KMeans
import numpy as np
import csv
import math
import matplotlib.pyplot
from matplotlib import pyplot as plt

In [3]:
maxAcc = 0.0
maxIter = 0
C_Lambda = 0.03
TrainingPercent = 80
ValidationPercent = 10
TestPercent = 10
M = 10
PHI = []
IsSynthetic = False

In [4]:
#function for getting the target vector
def GetTargetVector(filePath):
    t = []
    with open(filePath, 'rU') as f:
        reader = csv.reader(f)
        for row in reader:  
            t.append(int(row[0]))
    #print("Raw Training Generated..")
    #print(t)
    return t

#function for generating raw data
def GenerateRawData(filePath, IsSynthetic):    
    dataMatrix = [] 
    with open(filePath, 'rU') as fi:
        reader = csv.reader(fi)
        for row in reader:
            dataRow = []
            for column in row:
                dataRow.append(float(column))
            dataMatrix.append(dataRow)   
    
    #if IsSynthetic == False :
        #dataMatrix = np.delete(dataMatrix, [5,6,7,8,9], axis=1)
    dataMatrix = np.transpose(dataMatrix)     
    #print ("Data Matrix Generated..")
    return dataMatrix

#function for generating training target
def GenerateTrainingTarget(rawTraining,TrainingPercent = 80):
    TrainingLen = int(math.ceil(len(rawTraining)*(TrainingPercent*0.01)))
    t           = rawTraining[:TrainingLen]
    #print(str(TrainingPercent) + "% Training Target Generated..")
    return t

#function for generating training datamatrix
def GenerateTrainingDataMatrix(rawData, TrainingPercent = 80):
    T_len = int(math.ceil(len(rawData[0])*0.01*TrainingPercent))
    d2 = rawData[:,0:T_len]
    #print(str(TrainingPercent) + "% Training Data Generated..")
    return d2

#function for generating generating validation data array
def GenerateValData(rawData, ValPercent, TrainingCount): 
    valSize = int(math.ceil(len(rawData[0])*ValPercent*0.01))
    V_End = TrainingCount + valSize
    dataMatrix = rawData[:,TrainingCount+1:V_End]
    #print (str(ValPercent) + "% Val Data Generated..")  
    return dataMatrix

#function for generating validation target vector
def GenerateValTargetVector(rawData, ValPercent, TrainingCount): 
    valSize = int(math.ceil(len(rawData)*ValPercent*0.01))
    V_End = TrainingCount + valSize
    t =rawData[TrainingCount+1:V_End]
    #print (str(ValPercent) + "% Val Target Data Generated..")
    return t

#function for generating big sigma
def GenerateBigSigma(Data, MuMatrix,TrainingPercent,IsSynthetic):
    BigSigma    = np.zeros((len(Data),len(Data)))
    DataT       = np.transpose(Data)
    TrainingLen = math.ceil(len(DataT)*(TrainingPercent*0.01))        
    varVect     = []
    for i in range(0,len(DataT[0])):
        vct = []
        for j in range(0,int(TrainingLen)):
            vct.append(Data[i][j])    
        varVect.append(np.var(vct))
    
    for j in range(len(Data)):
        BigSigma[j][j] = varVect[j]
    if IsSynthetic == True:
        BigSigma = np.dot(3,BigSigma)
    else:
        BigSigma = np.dot(200,BigSigma)
    ##print ("BigSigma Generated..")
    return BigSigma

#function for getting scalar
def GetScalar(DataRow,MuRow, BigSigInv):  
    R = np.subtract(DataRow,MuRow)
    T = np.dot(BigSigInv,np.transpose(R))  
    L = np.dot(R,T)
    return L

#function for getting the gaussian radial basis
def GetRadialBasisOut(DataRow,MuRow, BigSigInv):    
    phi_x = math.exp(-0.5*GetScalar(DataRow,MuRow,BigSigInv))
    return phi_x

#function for getting the phi matrix
def GetPhiMatrix(Data, MuMatrix, BigSigma, TrainingPercent = 80):
    DataT = np.transpose(Data)
    TrainingLen = math.ceil(len(DataT)*(TrainingPercent*0.01))         
    PHI = np.zeros((int(TrainingLen),len(MuMatrix))) 
    BigSigInv = np.linalg.inv(BigSigma)
    for  C in range(0,len(MuMatrix)):
        for R in range(0,int(TrainingLen)):
            PHI[R][C] = GetRadialBasisOut(DataT[R], MuMatrix[C], BigSigInv)
    #print ("PHI Generated..")
    return PHI

#function for getting weights closed form
def GetWeightsClosedForm(PHI, T, Lambda):
    Lambda_I = np.identity(len(PHI[0]))
    for i in range(0,len(PHI[0])):
        Lambda_I[i][i] = Lambda
    PHI_T       = np.transpose(PHI)
    PHI_SQR     = np.dot(PHI_T,PHI)
    PHI_SQR_LI  = np.add(Lambda_I,PHI_SQR)
    PHI_SQR_INV = np.linalg.inv(PHI_SQR_LI)
    INTER       = np.dot(PHI_SQR_INV, PHI_T)
    W           = np.dot(INTER, T)
    ##print ("Training Weights Generated..")
    return W

#function for getting phi matrix
def GetPhiMatrix(Data, MuMatrix, BigSigma, TrainingPercent = 80):
    DataT = np.transpose(Data)
    TrainingLen = math.ceil(len(DataT)*(TrainingPercent*0.01))         
    PHI = np.zeros((int(TrainingLen),len(MuMatrix))) 
    BigSigInv = np.linalg.inv(BigSigma)
    for  C in range(0,len(MuMatrix)):
        for R in range(0,int(TrainingLen)):
            PHI[R][C] = GetRadialBasisOut(DataT[R], MuMatrix[C], BigSigInv)
    #print ("PHI Generated..")
    return PHI

#function for getting y(x,w)
def GetValTest(VAL_PHI,W):
    Y = np.dot(W,np.transpose(VAL_PHI))
    ##print ("Test Out Generated..")
    return Y
#function for getting the erms
def GetErms(VAL_TEST_OUT,ValDataAct):
    sum = 0.0
    t=0
    accuracy = 0.0
    counter = 0
    val = 0.0
    for i in range (0,len(VAL_TEST_OUT)):
        sum = sum + math.pow((ValDataAct[i] - VAL_TEST_OUT[i]),2)
        if(int(np.around(VAL_TEST_OUT[i], 0)) == ValDataAct[i]):
            counter+=1
    accuracy = (float((counter*100))/float(len(VAL_TEST_OUT)))
    ##print ("Accuracy Generated..")
    ##print ("Validation E_RMS : " + str(math.sqrt(sum/len(VAL_TEST_OUT))))
    return (str(accuracy) + ',' +  str(math.sqrt(sum/len(VAL_TEST_OUT))))

# Fetch and Prepare Dataset

In [78]:
RawTarget = GetTargetVector('same_diff_pairs_t.csv')
RawData_Concat   = GenerateRawData('Same_Diff_Feature_Concat_withoutlabel.csv',IsSynthetic)
RawData_Subtract   = GenerateRawData('Same_Diff_Feature_Subtract_withoutlabel.csv',IsSynthetic)

C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: 'U' mode is deprecated
  after removing the cwd from sys.path.
C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: 'U' mode is deprecated
  from ipykernel import kernelapp as app

# Prepare Training Data

In [79]:
TrainingTarget = np.array(GenerateTrainingTarget(RawTarget,TrainingPercent))
TrainingData_Concat   = GenerateTrainingDataMatrix(RawData_Concat,TrainingPercent)
TrainingData_Subtract   = GenerateTrainingDataMatrix(RawData_Subtract,TrainingPercent)

print(TrainingTarget.shape)
print(TrainingData_Concat.shape)
print(TrainingData_Subtract.shape)

(235059,)
(18, 235059)
(9, 235059)

# Prepare Validation Data

In [89]:
ValDataAct = np.array(GenerateValTargetVector(RawTarget,ValidationPercent, (len(TrainingTarget))))
ValData_Concat    = GenerateValData(RawData_Concat,ValidationPercent, (len(TrainingTarget)))
ValData_Subtract    = GenerateValData(RawData_Subtract,ValidationPercent, (len(TrainingTarget)))

print(ValDataAct.shape)
print(ValData_Concat.shape)
print(ValData_Subtract.shape)

(29382,)
(18, 29382)
(9, 29382)

# Prepare Test Data

In [90]:
TestDataAct = np.array(GenerateValTargetVector(RawTarget,TestPercent, (len(TrainingTarget)+len(ValDataAct))))
TestData_Concat = GenerateValData(RawData_Concat,TestPercent, (len(TrainingTarget)+len(ValDataAct)))
TestData_Subtract = GenerateValData(RawData_Subtract,TestPercent, (len(TrainingTarget)+len(ValDataAct)))

print(TestDataAct.shape)
print(TestData_Concat.shape)
print(TestData_Subtract.shape)

(29381,)
(18, 29381)
(9, 29381)

## Closed Form Solution [Finding Weights using Moore- Penrose pseudo- Inverse Matrix]
## Feature Concatenation

In [79]:
#Setting up the parameters.
maxAcc = 0.0
maxIter = 0
C_Lambda = 0.03
TrainingPercent = 80
ValidationPercent = 10
TestPercent = 10
M = 10
PHI = []
IsSynthetic = False

ErmsArr = []
AccuracyArr = []

kmeans = KMeans(n_clusters=M, random_state=0).fit(np.transpose(TrainingData_Concat))
Mu = kmeans.cluster_centers_

BigSigma     = GenerateBigSigma(RawData_Concat, Mu, TrainingPercent,IsSynthetic)
TRAINING_PHI = GetPhiMatrix(RawData_Concat, Mu, BigSigma, TrainingPercent)
W            = GetWeightsClosedForm(TRAINING_PHI,TrainingTarget,(C_Lambda)) 
TEST_PHI     = GetPhiMatrix(TestData_Concat, Mu, BigSigma, 100) 
VAL_PHI      = GetPhiMatrix(ValData_Concat, Mu, BigSigma, 100)

In [80]:
print(Mu.shape)
print(BigSigma.shape)
print(TRAINING_PHI.shape)
print(W.shape)
print(VAL_PHI.shape)
print(TEST_PHI.shape)

(10, 13)
(13, 13)
(235059, 10)
(10,)
(29382, 10)
(29381, 10)

# Finding Erms on training, validation and test set [Feature Concatenation]

In [71]:
TR_TEST_OUT  = GetValTest(TRAINING_PHI,W)
VAL_TEST_OUT = GetValTest(VAL_PHI,W)
TEST_OUT     = GetValTest(TEST_PHI,W)

TrainingAccuracy   = str(GetErms(TR_TEST_OUT,TrainingTarget))
ValidationAccuracy = str(GetErms(VAL_TEST_OUT,ValDataAct))
TestAccuracy       = str(GetErms(TEST_OUT,TestDataAct))

In [81]:
print ('UBITname      = rikhan')
print ('Person Number = 50210680')
print ('----------------------------------------------------')
print ("------------------CEDAR Letter Data------------------------")
print ('----------------------------------------------------')
print ("-------Closed Form with Radial Basis Function-------")
print ("----------------Feature Concatenation---------------")

print ('----------------------------------------------------')
print ("M = 10 \nLambda = 0.03")
print ("E_rms Training   = " + str(float(TrainingAccuracy.split(',')[1])))
print ("E_rms Validation = " + str(float(ValidationAccuracy.split(',')[1])))
print ("E_rms Testing    = " + str(float(TestAccuracy.split(',')[1])))

UBITname      = rikhan
Person Number = 50210680
----------------------------------------------------
------------------CEDAR Letter Data------------------------
----------------------------------------------------
-------Closed Form with Radial Basis Function-------
----------------Feature Concatenation---------------
----------------------------------------------------
M = 10
Lambda = 0.03
E_rms Training   = 0.05768044755871531
E_rms Validation = 0.00554583050653763
E_rms Testing    = 0.005115535475391802

# Gradient Descent Solution for Linear Regression
## Feature Concatenation

In [101]:
print ('----------------------------------------------------')
print ('--------------Please Wait for 12 mins!----------------')
print ('----------------------------------------------------')

----------------------------------------------------
--------------Please Wait for 12 mins!----------------
----------------------------------------------------

In [82]:
W_Now        = np.dot(220, W)
La           = 2
learningRate = 0.01
L_Erms_Val   = []
L_Erms_TR    = []
L_Erms_Test  = []
W_Mat        = []

for i in range(0,400):
    
    #print ('---------Iteration: ' + str(i) + '--------------')
    Delta_E_D     = -np.dot((TrainingTarget[i] - np.dot(np.transpose(W_Now),TRAINING_PHI[i])),TRAINING_PHI[i])
    La_Delta_E_W  = np.dot(La,W_Now)
    Delta_E       = np.add(Delta_E_D,La_Delta_E_W)    
    Delta_W       = -np.dot(learningRate,Delta_E)
    W_T_Next      = W_Now + Delta_W
    W_Now         = W_T_Next
    
    #-----------------TrainingData Accuracy---------------------#
    TR_TEST_OUT   = GetValTest(TRAINING_PHI,W_T_Next) 
    Erms_TR       = GetErms(TR_TEST_OUT,TrainingTarget)
    L_Erms_TR.append(float(Erms_TR.split(',')[1]))
    
    #-----------------ValidationData Accuracy---------------------#
    VAL_TEST_OUT  = GetValTest(VAL_PHI,W_T_Next) 
    Erms_Val      = GetErms(VAL_TEST_OUT,ValDataAct)
    L_Erms_Val.append(float(Erms_Val.split(',')[1]))
    
    #-----------------TestingData Accuracy---------------------#
    TEST_OUT      = GetValTest(TEST_PHI,W_T_Next) 
    Erms_Test = GetErms(TEST_OUT,TestDataAct)
    L_Erms_Test.append(float(Erms_Test.split(',')[1]))

In [83]:
print ('----------Gradient Descent Solution--------------------')
print ("----------------Feature Concatenation------------------")
print ("-----------------neta=0.01-----------------------------")
print ("E_rms Training   = " + str(np.around(min(L_Erms_TR),5)))
print ("E_rms Validation = " + str(np.around(min(L_Erms_Val),5)))
print ("E_rms Testing    = " + str(np.around(min(L_Erms_Test),5)))

----------Gradient Descent Solution--------------------
----------------Feature Concatenation------------------
-----------------neta=0.01-----------------------------
E_rms Training   = 0.27069
E_rms Validation = 0.25912
E_rms Testing    = 0.23591

## Closed Form Solution [Finding Weights using Moore- Penrose pseudo- Inverse Matrix]
## Feature Subtraction

In [93]:
#Setting up the parameters.
maxAcc = 0.0
maxIter = 0
C_Lambda = 0.03
TrainingPercent = 80
ValidationPercent = 10
TestPercent = 10
M = 10
PHI = []
IsSynthetic = False

ErmsArr = []
AccuracyArr = []

kmeans = KMeans(n_clusters=M, random_state=0).fit(np.transpose(TrainingData_Subtract))
Mu = kmeans.cluster_centers_

BigSigma     = GenerateBigSigma(RawData_Subtract, Mu, TrainingPercent,IsSynthetic)
TRAINING_PHI = GetPhiMatrix(RawData_Subtract, Mu, BigSigma, TrainingPercent)
W            = GetWeightsClosedForm(TRAINING_PHI,TrainingTarget,(C_Lambda)) 
TEST_PHI     = GetPhiMatrix(TestData_Subtract, Mu, BigSigma, 100) 
VAL_PHI      = GetPhiMatrix(ValData_Subtract, Mu, BigSigma, 100)

In [94]:
print(Mu.shape)
print(BigSigma.shape)
print(TRAINING_PHI.shape)
print(W.shape)
print(VAL_PHI.shape)
print(TEST_PHI.shape)

(10, 9)
(9, 9)
(235059, 10)
(10,)
(29382, 10)
(29381, 10)

# Finding Erms on training, validation and test set [Feature Subtraction]

In [95]:
TR_TEST_OUT  = GetValTest(TRAINING_PHI,W)
VAL_TEST_OUT = GetValTest(VAL_PHI,W)
TEST_OUT     = GetValTest(TEST_PHI,W)

TrainingAccuracy   = str(GetErms(TR_TEST_OUT,TrainingTarget))
ValidationAccuracy = str(GetErms(VAL_TEST_OUT,ValDataAct))
TestAccuracy       = str(GetErms(TEST_OUT,TestDataAct))

In [96]:
print ('----------------------------------------------------')
print ("-------Closed Form with Radial Basis Function-------")
print ("----------------Feature Subtraction---------------")

print ('----------------------------------------------------')
print ("M = 10 \nLambda = 0.03")
print ("E_rms Training   = " + str(float(TrainingAccuracy.split(',')[1])))
print ("E_rms Validation = " + str(float(ValidationAccuracy.split(',')[1])))
print ("E_rms Testing    = " + str(float(TestAccuracy.split(',')[1])))

----------------------------------------------------
-------Closed Form with Radial Basis Function-------
----------------Feature Subtraction---------------
----------------------------------------------------
M = 10
Lambda = 0.03
E_rms Training   = 0.057779665546661654
E_rms Validation = 0.0038188729742869363
E_rms Testing    = 0.0037147085224796417

# Gradient Descent Solution for Linear Regression
## Feature Subtraction

In [100]:
print ('----------------------------------------------------')
print ('--------------Please Wait for 12 mins!----------------')
print ('----------------------------------------------------')

----------------------------------------------------
--------------Please Wait for 12 mins!----------------
----------------------------------------------------

In [99]:
W_Now        = np.dot(220, W)
La           = 2
learningRate = 0.01
L_Erms_Val   = []
L_Erms_TR    = []
L_Erms_Test  = []
W_Mat        = []

for i in range(0,400):
    
    #print ('---------Iteration: ' + str(i) + '--------------')
    Delta_E_D     = -np.dot((TrainingTarget[i] - np.dot(np.transpose(W_Now),TRAINING_PHI[i])),TRAINING_PHI[i])
    La_Delta_E_W  = np.dot(La,W_Now)
    Delta_E       = np.add(Delta_E_D,La_Delta_E_W)    
    Delta_W       = -np.dot(learningRate,Delta_E)
    W_T_Next      = W_Now + Delta_W
    W_Now         = W_T_Next
    
    #-----------------TrainingData Accuracy---------------------#
    TR_TEST_OUT   = GetValTest(TRAINING_PHI,W_T_Next) 
    Erms_TR       = GetErms(TR_TEST_OUT,TrainingTarget)
    L_Erms_TR.append(float(Erms_TR.split(',')[1]))
    
    #-----------------ValidationData Accuracy---------------------#
    VAL_TEST_OUT  = GetValTest(VAL_PHI,W_T_Next) 
    Erms_Val      = GetErms(VAL_TEST_OUT,ValDataAct)
    L_Erms_Val.append(float(Erms_Val.split(',')[1]))
    
    #-----------------TestingData Accuracy---------------------#
    TEST_OUT      = GetValTest(TEST_PHI,W_T_Next) 
    Erms_Test = GetErms(TEST_OUT,TestDataAct)
    L_Erms_Test.append(float(Erms_Test.split(',')[1]))

In [102]:
print ('----------Gradient Descent Solution--------------------')
print ("----------------Feature Subtraction------------------")
print ("-----------------neta=0.01-----------------------------")
print ("E_rms Training   = " + str(np.around(min(L_Erms_TR),5)))
print ("E_rms Validation = " + str(np.around(min(L_Erms_Val),5)))
print ("E_rms Testing    = " + str(np.around(min(L_Erms_Test),5)))

----------Gradient Descent Solution--------------------
----------------Feature Subtraction------------------
-----------------neta=0.01-----------------------------
E_rms Training   = 0.43266
E_rms Validation = 0.36752
E_rms Testing    = 0.35043

# Feature Extraction From GSC Raw Data

In [5]:
gsc_same_diff_pair = pd.read_csv('gsc_same_diff_pairs.csv')

In [6]:
gsc_same_diff_pair.head()

         img_id_A        img_id_B
0  0001a_num1.png  0001a_num2.png
1  0001a_num1.png  0001a_num3.png
2  0001a_num1.png  0001a_num4.png
3  0001a_num1.png  0001a_num5.png
4  0001a_num1.png  0001b_num1.png

In [7]:
gsc_same_diff_pair.columns

Index(['img_id_A', 'img_id_B'], dtype='object')

In [8]:
gsc_same_diff_pair.tail()

              img_id_A        img_id_B
199994  0264c_num1.png  0321c_num3.png
199995  0264c_num1.png  0321c_num4.png
199996  0264c_num1.png  0322b_num1.png
199997  0264c_num1.png  0323a_num1.png
199998  0264c_num1.png  0323a_num2.png

In [13]:
gsc_feature_list = pd.read_csv('GSC-Features.csv')

In [14]:
#working with 100 features only to save space and time. 
for i in range(101,513):
    gsc_feature_list=gsc_feature_list.drop(columns=['f'+str(i)])

In [15]:
gsc_feature_list.head()

,img_id,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f91,f92,f93,f94,f95,f96,f97,f98,f99,f100
0,0001a_num1.png,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,1,0,0
1,0001a_num2.png,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,1,1,0,0,0
2,0001a_num3.png,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,0,0
3,0001a_num4.png,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,1,0,1,0
4,0001a_num5.png,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,1,1,1,0

In [16]:
gsc_temp = gsc_same_diff_pair.merge(gsc_feature_list, how='inner', left_on='img_id_A', right_on='img_id')
gsc_temp = gsc_temp.drop(columns=['img_id'])
gsc_temp.head(2)

,img_id_A,img_id_B,f1,f2,f3,f4,f5,f6,f7,f8,...,f91,f92,f93,f94,f95,f96,f97,f98,f99,f100
0,0001a_num1.png,0001a_num2.png,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,1,0,0
1,0001a_num1.png,0001a_num3.png,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,1,0,0

In [17]:
gsc_merged_df = gsc_temp.merge(gsc_feature_list, how='inner', left_on='img_id_B', right_on='img_id')
gsc_merged_df = gsc_merged_df.drop(columns=['img_id'])
gsc_merged_df.head(2)

,img_id_A,img_id_B,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,f8_x,...,f91_y,f92_y,f93_y,f94_y,f95_y,f96_y,f97_y,f98_y,f99_y,f100_y
0,0001a_num1.png,0001a_num2.png,0,0,0,0,0,0,0,0,...,1,1,0,0,0,1,1,0,0,0
1,0001a_num1.png,0001a_num3.png,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,0,0

In [18]:
gsc_merged_df.to_csv('GSC_Same_Diff_Feature_Concat.csv')

In [19]:
gsc_merged_df = gsc_merged_df.drop(columns=['img_id_A','img_id_B'])

In [20]:
gsc_merged_df.head()

,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,f8_x,f9_x,f10_x,...,f91_y,f92_y,f93_y,f94_y,f95_y,f96_y,f97_y,f98_y,f99_y,f100_y
0,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,1,1,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,1,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,1,0,1,0

In [21]:
gsc_merged_df.to_csv('GSC_Same_Diff_Feature_Concat_withoutlabel_raw.csv')
#Index labels removed manually to make a matrix.

In [22]:
GSC_Same_Diff_merged_df = pd.read_csv('GSC_Same_Diff_Feature_Concat_withoutlabel.csv')

In [35]:
gsc_merged_subtract_df = pd.read_csv('GSC_Same_Diff_Feature_Concat.csv')

In [36]:
gsc_merged_subtract_df.head()

,Unnamed: 0,img_id_A,img_id_B,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,...,f91_y,f92_y,f93_y,f94_y,f95_y,f96_y,f97_y,f98_y,f99_y,f100_y
0,0,0001a_num1.png,0001a_num2.png,0,0,0,0,0,0,0,...,1,1,0,0,0,1,1,0,0,0
1,1,0001a_num1.png,0001a_num3.png,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,0,0
2,2,0001a_num2.png,0001a_num3.png,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,0,0
3,3,0001a_num1.png,0001a_num4.png,0,0,0,0,0,0,0,...,1,1,0,0,0,0,1,0,1,0
4,4,0001a_num2.png,0001a_num4.png,0,0,0,0,0,0,0,...,1,1,0,0,0,0,1,0,1,0

In [37]:
gsc_merged_subtract_df = gsc_merged_subtract_df.drop(columns=['Unnamed: 0'])

In [38]:
gsc_merged_subtract_df.head()

,img_id_A,img_id_B,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,f8_x,...,f91_y,f92_y,f93_y,f94_y,f95_y,f96_y,f97_y,f98_y,f99_y,f100_y
0,0001a_num1.png,0001a_num2.png,0,0,0,0,0,0,0,0,...,1,1,0,0,0,1,1,0,0,0
1,0001a_num1.png,0001a_num3.png,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,0,0
2,0001a_num2.png,0001a_num3.png,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,0,0
3,0001a_num1.png,0001a_num4.png,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,1,0,1,0
4,0001a_num2.png,0001a_num4.png,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,1,0,1,0

In [39]:
for i in range(1,101):
    gsc_merged_subtract_df['f'+str(i)+'_x'] = abs(gsc_merged_subtract_df['f'+str(i)+'_x']- gsc_merged_subtract_df['f'+str(i)+'_y'])

In [40]:
for i in range(1,101):
    gsc_merged_subtract_df = gsc_merged_subtract_df.drop(columns=['f'+str(i)+'_y'])

In [41]:
gsc_merged_subtract_df.head()

,img_id_A,img_id_B,f1_x,f2_x,f3_x,f4_x,f5_x,f6_x,f7_x,f8_x,...,f91_x,f92_x,f93_x,f94_x,f95_x,f96_x,f97_x,f98_x,f99_x,f100_x
0,0001a_num1.png,0001a_num2.png,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,1,0,0
1,0001a_num1.png,0001a_num3.png,0,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,0,0,0
2,0001a_num2.png,0001a_num3.png,0,0,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,0,0
3,0001a_num1.png,0001a_num4.png,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,1,0
4,0001a_num2.png,0001a_num4.png,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0

In [42]:
gsc_merged_subtract_df.to_csv('GSC_Same_Diff_Feature_Subtract.csv')

In [43]:
gsc_merged_subtract_df = gsc_merged_subtract_df.drop(columns=['img_id_A','img_id_B'])

In [44]:
gsc_merged_subtract_df.to_csv('GSC_Same_Diff_Feature_Subtract_withoutlabel_raw.csv')

In [45]:
gsc_merged_subtract_df = pd.read_csv('GSC_Same_Diff_Feature_Subtract_withoutlabel.csv')

In [46]:
gsc_merged_concat_df = pd.read_csv('GSC_Same_Diff_Feature_Concat_withoutlabel.csv')

# Initializing Parameters

In [ ]:
maxAcc = 0.0
maxIter = 0
C_Lambda = 0.03
TrainingPercent = 80
ValidationPercent = 10
TestPercent = 10
M = 10
PHI = []
IsSynthetic = False

# Fetch and Prepare Dataset

In [49]:
RawTarget = GetTargetVector('gsc_same_diff_pairs_t.csv')
RawData_Concat   = GenerateRawData('GSC_Same_Diff_Feature_Concat_withoutlabel.csv',IsSynthetic)
RawData_Subtract   = GenerateRawData('GSC_Same_Diff_Feature_Subtract_withoutlabel.csv',IsSynthetic)

C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: 'U' mode is deprecated
  after removing the cwd from sys.path.
C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: 'U' mode is deprecated
  from ipykernel import kernelapp as app

# Prepare Training Data

In [50]:
TrainingTarget = np.array(GenerateTrainingTarget(RawTarget,TrainingPercent))
TrainingData_Concat   = GenerateTrainingDataMatrix(RawData_Concat,TrainingPercent)
TrainingData_Subtract   = GenerateTrainingDataMatrix(RawData_Subtract,TrainingPercent)

print(TrainingTarget.shape)
print(TrainingData_Concat.shape)
print(TrainingData_Subtract.shape)

(160000,)
(200, 160000)
(100, 160000)

# Prepare Validation Data

In [51]:
ValDataAct = np.array(GenerateValTargetVector(RawTarget,ValidationPercent, (len(TrainingTarget))))
ValData_Concat    = GenerateValData(RawData_Concat,ValidationPercent, (len(TrainingTarget)))
ValData_Subtract    = GenerateValData(RawData_Subtract,ValidationPercent, (len(TrainingTarget)))

print(ValDataAct.shape)
print(ValData_Concat.shape)
print(ValData_Subtract.shape)

(19999,)
(200, 19999)
(100, 19999)

# Prepare Testing Data

In [52]:
TestDataAct = np.array(GenerateValTargetVector(RawTarget,TestPercent, (len(TrainingTarget)+len(ValDataAct))))
TestData_Concat = GenerateValData(RawData_Concat,TestPercent, (len(TrainingTarget)+len(ValDataAct)))
TestData_Subtract = GenerateValData(RawData_Subtract,TestPercent, (len(TrainingTarget)+len(ValDataAct)))

print(TestDataAct.shape)
print(TestData_Concat.shape)
print(TestData_Subtract.shape)

(19999,)
(200, 19999)
(100, 19999)

## Closed Form Solution [Finding Weights using Moore- Penrose pseudo- Inverse Matrix]
## GSC Feature Concatenation

In [53]:
#Setting up the parameters.
maxAcc = 0.0
maxIter = 0
C_Lambda = 0.03
TrainingPercent = 80
ValidationPercent = 10
TestPercent = 10
M = 10
PHI = []
IsSynthetic = False

ErmsArr = []
AccuracyArr = []

kmeans = KMeans(n_clusters=M, random_state=0).fit(np.transpose(TrainingData_Concat))
Mu = kmeans.cluster_centers_

BigSigma     = GenerateBigSigma(RawData_Concat, Mu, TrainingPercent,IsSynthetic)
TRAINING_PHI = GetPhiMatrix(RawData_Concat, Mu, BigSigma, TrainingPercent)
W            = GetWeightsClosedForm(TRAINING_PHI,TrainingTarget,(C_Lambda)) 
TEST_PHI     = GetPhiMatrix(TestData_Concat, Mu, BigSigma, 100) 
VAL_PHI      = GetPhiMatrix(ValData_Concat, Mu, BigSigma, 100)

In [54]:
print(Mu.shape)
print(BigSigma.shape)
print(TRAINING_PHI.shape)
print(W.shape)
print(VAL_PHI.shape)
print(TEST_PHI.shape)

(10, 200)
(200, 200)
(160000, 10)
(10,)
(19999, 10)
(19999, 10)

# Finding Erms on training, validation and test set [Feature Concatenation]

In [55]:
TR_TEST_OUT  = GetValTest(TRAINING_PHI,W)
VAL_TEST_OUT = GetValTest(VAL_PHI,W)
TEST_OUT     = GetValTest(TEST_PHI,W)

TrainingAccuracy   = str(GetErms(TR_TEST_OUT,TrainingTarget))
ValidationAccuracy = str(GetErms(VAL_TEST_OUT,ValDataAct))
TestAccuracy       = str(GetErms(TEST_OUT,TestDataAct))

In [56]:
print ("-------Closed Form with Radial Basis Function-------")
print ("------------GSC Feature Concatenation---------------")

print ('----------------------------------------------------')
print ("M = 10 \nLambda = 0.03")
print ("E_rms Training   = " + str(float(TrainingAccuracy.split(',')[1])))
print ("E_rms Validation = " + str(float(ValidationAccuracy.split(',')[1])))
print ("E_rms Testing    = " + str(float(TestAccuracy.split(',')[1])))

-------Closed Form with Radial Basis Function-------
------------GSC Feature Concatenation---------------
----------------------------------------------------
M = 10
Lambda = 0.03
E_rms Training   = 0.4987388325281887
E_rms Validation = 0.4189130017090638
E_rms Testing    = 0.4267765618710845

# Gradient Descent Solution for Linear Regression
## GSC Feature Concatenation

In [57]:
print ('----------------------------------------------------')
print ('--------------Please Wait for 12 mins!----------------')
print ('----------------------------------------------------')

----------------------------------------------------
--------------Please Wait for 12 mins!----------------
----------------------------------------------------

In [58]:
W_Now        = np.dot(220, W)
La           = 2
learningRate = 0.01
L_Erms_Val   = []
L_Erms_TR    = []
L_Erms_Test  = []
W_Mat        = []

for i in range(0,200):
    
    #print ('---------Iteration: ' + str(i) + '--------------')
    Delta_E_D     = -np.dot((TrainingTarget[i] - np.dot(np.transpose(W_Now),TRAINING_PHI[i])),TRAINING_PHI[i])
    La_Delta_E_W  = np.dot(La,W_Now)
    Delta_E       = np.add(Delta_E_D,La_Delta_E_W)    
    Delta_W       = -np.dot(learningRate,Delta_E)
    W_T_Next      = W_Now + Delta_W
    W_Now         = W_T_Next
    
    #-----------------TrainingData Accuracy---------------------#
    TR_TEST_OUT   = GetValTest(TRAINING_PHI,W_T_Next) 
    Erms_TR       = GetErms(TR_TEST_OUT,TrainingTarget)
    L_Erms_TR.append(float(Erms_TR.split(',')[1]))
    
    #-----------------ValidationData Accuracy---------------------#
    VAL_TEST_OUT  = GetValTest(VAL_PHI,W_T_Next) 
    Erms_Val      = GetErms(VAL_TEST_OUT,ValDataAct)
    L_Erms_Val.append(float(Erms_Val.split(',')[1]))
    
    #-----------------TestingData Accuracy---------------------#
    TEST_OUT      = GetValTest(TEST_PHI,W_T_Next) 
    Erms_Test = GetErms(TEST_OUT,TestDataAct)
    L_Erms_Test.append(float(Erms_Test.split(',')[1]))

In [59]:
print ('----------Gradient Descent Solution--------------------')
print ("----------------GSC Feature Concatenation---------------")
print ("-----------------neta=0.01-----------------------------")
print ("E_rms Training   = " + str(np.around(min(L_Erms_TR),5)))
print ("E_rms Validation = " + str(np.around(min(L_Erms_Val),5)))
print ("E_rms Testing    = " + str(np.around(min(L_Erms_Test),5)))

----------Gradient Descent Solution--------------------
----------------GSC Feature Concatenation---------------
-----------------neta=0.01-----------------------------
E_rms Training   = 0.68055
E_rms Validation = 0.43864
E_rms Testing    = 0.4279

## Closed Form Solution [Finding Weights using Moore- Penrose pseudo- Inverse Matrix]
## GSC Feature Subtraction

In [60]:
#Setting up the parameters.
maxAcc = 0.0
maxIter = 0
C_Lambda = 0.03
TrainingPercent = 80
ValidationPercent = 10
TestPercent = 10
M = 10
PHI = []
IsSynthetic = False

ErmsArr = []
AccuracyArr = []

kmeans = KMeans(n_clusters=M, random_state=0).fit(np.transpose(TrainingData_Subtract))
Mu = kmeans.cluster_centers_

BigSigma     = GenerateBigSigma(RawData_Subtract, Mu, TrainingPercent,IsSynthetic)
TRAINING_PHI = GetPhiMatrix(RawData_Subtract, Mu, BigSigma, TrainingPercent)
W            = GetWeightsClosedForm(TRAINING_PHI,TrainingTarget,(C_Lambda)) 
TEST_PHI     = GetPhiMatrix(TestData_Subtract, Mu, BigSigma, 100) 
VAL_PHI      = GetPhiMatrix(ValData_Subtract, Mu, BigSigma, 100)

In [61]:
print(Mu.shape)
print(BigSigma.shape)
print(TRAINING_PHI.shape)
print(W.shape)
print(VAL_PHI.shape)
print(TEST_PHI.shape)

(10, 100)
(100, 100)
(160000, 10)
(10,)
(19999, 10)
(19999, 10)

## Finding Erms on training, validation and test set [GSC Feature Subtraction]

In [63]:
TR_TEST_OUT  = GetValTest(TRAINING_PHI,W)
VAL_TEST_OUT = GetValTest(VAL_PHI,W)
TEST_OUT     = GetValTest(TEST_PHI,W)

TrainingAccuracy   = str(GetErms(TR_TEST_OUT,TrainingTarget))
ValidationAccuracy = str(GetErms(VAL_TEST_OUT,ValDataAct))
TestAccuracy       = str(GetErms(TEST_OUT,TestDataAct))

In [64]:
print ('----------------------------------------------------')
print ("-------Closed Form with Radial Basis Function-------")
print ("----------------GSC Feature Subtraction---------------")

print ('----------------------------------------------------')
print ("M = 10 \nLambda = 0.03")
print ("E_rms Training   = " + str(float(TrainingAccuracy.split(',')[1])))
print ("E_rms Validation = " + str(float(ValidationAccuracy.split(',')[1])))
print ("E_rms Testing    = " + str(float(TestAccuracy.split(',')[1])))

----------------------------------------------------
-------Closed Form with Radial Basis Function-------
----------------GSC Feature Subtraction---------------
----------------------------------------------------
M = 10
Lambda = 0.03
E_rms Training   = 0.4912013881428152
E_rms Validation = 0.40279500687719844
E_rms Testing    = 0.40927877750343133

# Gradient Descent Solution for Linear Regression
## GSC Feature Subtraction

In [65]:
print ('----------------------------------------------------')
print ('--------------Please Wait for 12 mins!----------------')
print ('----------------------------------------------------')

----------------------------------------------------
--------------Please Wait for 12 mins!----------------
----------------------------------------------------

In [66]:
W_Now        = np.dot(220, W)
La           = 2
learningRate = 0.01
L_Erms_Val   = []
L_Erms_TR    = []
L_Erms_Test  = []
W_Mat        = []

for i in range(0,200):
    
    #print ('---------Iteration: ' + str(i) + '--------------')
    Delta_E_D     = -np.dot((TrainingTarget[i] - np.dot(np.transpose(W_Now),TRAINING_PHI[i])),TRAINING_PHI[i])
    La_Delta_E_W  = np.dot(La,W_Now)
    Delta_E       = np.add(Delta_E_D,La_Delta_E_W)    
    Delta_W       = -np.dot(learningRate,Delta_E)
    W_T_Next      = W_Now + Delta_W
    W_Now         = W_T_Next
    
    #-----------------TrainingData Accuracy---------------------#
    TR_TEST_OUT   = GetValTest(TRAINING_PHI,W_T_Next) 
    Erms_TR       = GetErms(TR_TEST_OUT,TrainingTarget)
    L_Erms_TR.append(float(Erms_TR.split(',')[1]))
    
    #-----------------ValidationData Accuracy---------------------#
    VAL_TEST_OUT  = GetValTest(VAL_PHI,W_T_Next) 
    Erms_Val      = GetErms(VAL_TEST_OUT,ValDataAct)
    L_Erms_Val.append(float(Erms_Val.split(',')[1]))
    
    #-----------------TestingData Accuracy---------------------#
    TEST_OUT      = GetValTest(TEST_PHI,W_T_Next) 
    Erms_Test = GetErms(TEST_OUT,TestDataAct)
    L_Erms_Test.append(float(Erms_Test.split(',')[1]))

In [67]:
print ('----------Gradient Descent Solution--------------------')
print ("----------------GSC Feature Subtraction----------------")
print ("-----------------neta=0.01-----------------------------")
print ("E_rms Training   = " + str(np.around(min(L_Erms_TR),5)))
print ("E_rms Validation = " + str(np.around(min(L_Erms_Val),5)))
print ("E_rms Testing    = " + str(np.around(min(L_Erms_Test),5)))

----------Gradient Descent Solution--------------------
----------------GSC Feature Subtraction----------------
-----------------neta=0.01-----------------------------
E_rms Training   = 0.60355
E_rms Validation = 0.52785
E_rms Testing    = 0.54333

# LOGISTIC REGRESSION HUMAN OBSERVED FEATURES

In [25]:
#reference:  https://medium.com/@martinpella/logistic-regression-from-scratch-in-python-124c5636b8ac
class LogisticRegression:
    def __init__(self, lr=0.01, num_iter=100000, fit_intercept=True, verbose=False):
        self.lr = lr
        self.num_iter = num_iter
        self.fit_intercept = fit_intercept
        self.verbose = verbose
    
    def __add_intercept(self, X):
        intercept = np.ones((X.shape[0], 1))
        return np.concatenate((intercept, X), axis=1)
    
    def __sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def __loss(self, h, y):
        return (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()
    
    def fit(self, X, y):
        #if self.fit_intercept:
            #X = self.__add_intercept(X)
        
        # weights initialization
        self.theta = np.zeros(X.shape[0])
        
        for i in range(self.num_iter):
            z = np.dot(X.T, self.theta)
            h = self.__sigmoid(z)
            #print((X.T).shape)
            #print((np.transpose(X)).shape)
            #print('--------')
            #print(h-y)
            #print (h.shape,y.shape,X.shape)
            #print((h-y).shape)
            gradient = np.dot(X, (h - y))
           # gradient = (X.T *(h-y))
            gradient = gradient / y.size
            #gradient = (X.T *(h-y))/y.size
            self.theta -= self.lr * gradient
            
            if(self.verbose == True and i % 10000 == 0):
                z = np.dot(X, self.theta)
                h = self.__sigmoid(z)
                print(f'loss: {self.__loss(h, y)} \t')
    
    def predict_prob(self, X):
        #if self.fit_intercept:
            #X = self.__add_intercept(X)
    
        return self.__sigmoid(np.dot(X.T, self.theta))
    
    def predict(self, X):
        return self.predict_prob(X).round()

# Collecting Training, Validation and Testing Set

In [43]:
RawTarget = GetTargetVector('same_diff_pairs_t.csv')
RawData_Concat   = GenerateRawData('Same_Diff_Feature_Concat_withoutlabel.csv',IsSynthetic)
RawData_Subtract   = GenerateRawData('Same_Diff_Feature_Subtract_withoutlabel.csv',IsSynthetic)

TrainingTarget = np.array(GenerateTrainingTarget(RawTarget,TrainingPercent))
TrainingData_Concat   = GenerateTrainingDataMatrix(RawData_Concat,TrainingPercent)
TrainingData_Subtract   = GenerateTrainingDataMatrix(RawData_Subtract,TrainingPercent)

print(TrainingTarget.shape)
print(TrainingData_Concat.shape)
print(TrainingData_Subtract.shape)

ValDataAct = np.array(GenerateValTargetVector(RawTarget,ValidationPercent, (len(TrainingTarget))))
ValData_Concat    = GenerateValData(RawData_Concat,ValidationPercent, (len(TrainingTarget)))
ValData_Subtract    = GenerateValData(RawData_Subtract,ValidationPercent, (len(TrainingTarget)))

print(ValDataAct.shape)
print(ValData_Concat.shape)
print(ValData_Subtract.shape)

TestDataAct = np.array(GenerateValTargetVector(RawTarget,TestPercent, (len(TrainingTarget)+len(ValDataAct))))
TestData_Concat = GenerateValData(RawData_Concat,TestPercent, (len(TrainingTarget)+len(ValDataAct)))
TestData_Subtract = GenerateValData(RawData_Subtract,TestPercent, (len(TrainingTarget)+len(ValDataAct)))

print(TestDataAct.shape)
print(TestData_Concat.shape)
print(TestData_Subtract.shape)

C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: 'U' mode is deprecated
  after removing the cwd from sys.path.
C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: 'U' mode is deprecated
  from ipykernel import kernelapp as app

(235059,)
(18, 235059)
(9, 235059)
(29382,)
(18, 29382)
(9, 29382)
(29381,)
(18, 29381)
(9, 29381)

# Logistic Regression Model on Human Observed Subtracted Feature

In [38]:
model = LogisticRegression(lr=0.1, num_iter=300)
#%time model.fit(msd, res)
#TrainingData_Subtract = np.transpose(TrainingData_Subtract)
#TrainingTarget = np.transpose(TrainingTarget)
#print (TrainingData_Subtract.shape, TrainingTarget.shape)
X = TrainingData_Subtract
y = TrainingTarget
model.fit(X,y)
#CPU times: user 13.8 s, sys: 84 ms, total: 13.9 s
#Wall time: 13.8 s
V = ValData_Subtract
y_v = ValDataAct 
T = TestData_Subtract
y_t = TestDataAct
preds = model.predict(X)
preds_v = model.predict(V)
preds_t = model.predict(T)
# accuracy
#( preds == y).mean() 
print('--------LOGISTIC REGRESSION ON HUMAN OBSERVED DATASET---------------')
print('--------------------------FEATURE SUBTRACTION-----------------------')
print('prediction accuracy of Training set:'+ str((preds == y).mean()))
print('prediction accuracy of Validation set:'+ str((preds_v == y_v).mean()))
#(preds_v == y_v).mean()
print('prediction accuracy of Testing set:'+ str((preds_t == y_t).mean()))
#(preds_t == y).mean()
#1.0
#https://stackoverflow.com/questions/24560298/python-numpy-valueerror-operands-could-not-be-broadcast-together-with-shapes

--------LOGISTIC REGRESSION ON HUMAN OBSERVED DATASET---------------
--------------------------FEATURE SUBTRACTION-----------------------
prediction accuracy of Training set:0.9966348874112457
prediction accuracy of Validation set:1.0
prediction accuracy of Testing set:1.0

# Logistic Regression Model on Human Observed Concatenated Features

In [39]:
model = LogisticRegression(lr=0.1, num_iter=300)

X = TrainingData_Concat
y = TrainingTarget
model.fit(X,y)

V = ValData_Concat
y_v = ValDataAct 
T = TestData_Concat
y_t = TestDataAct
preds = model.predict(X)
preds_v = model.predict(V)
preds_t = model.predict(T)

print('--------LOGISTIC REGRESSION ON HUMAN OBSERVED DATASET---------------')
print('--------------------------FEATURE CONCATENATION-----------------------')

print('prediction accuracy of Training set:'+ str((preds == y).mean()))

print('prediction accuracy of Validation set:'+ str((preds_v == y_v).mean()))

print('prediction accuracy of Testing set:'+ str((preds_t == y_t).mean()))

--------LOGISTIC REGRESSION ON HUMAN OBSERVED DATASET---------------
--------------------------FEATURE CONCATENATION-----------------------
prediction accuracy of Training set:0.9966348874112457
prediction accuracy of Validation set:1.0
prediction accuracy of Testing set:1.0

# LOGISTIC REGRESSION GSC DATASET

# Collecting Training, Validation and Testing Sets

In [40]:
RawTarget = GetTargetVector('gsc_same_diff_pairs_t.csv')
RawData_Concat   = GenerateRawData('GSC_Same_Diff_Feature_Concat_withoutlabel.csv',IsSynthetic)
RawData_Subtract   = GenerateRawData('GSC_Same_Diff_Feature_Subtract_withoutlabel.csv',IsSynthetic)

TrainingTarget = np.array(GenerateTrainingTarget(RawTarget,TrainingPercent))
TrainingData_Concat   = GenerateTrainingDataMatrix(RawData_Concat,TrainingPercent)
TrainingData_Subtract   = GenerateTrainingDataMatrix(RawData_Subtract,TrainingPercent)

print(TrainingTarget.shape)
print(TrainingData_Concat.shape)
print(TrainingData_Subtract.shape)

ValDataAct = np.array(GenerateValTargetVector(RawTarget,ValidationPercent, (len(TrainingTarget))))
ValData_Concat    = GenerateValData(RawData_Concat,ValidationPercent, (len(TrainingTarget)))
ValData_Subtract    = GenerateValData(RawData_Subtract,ValidationPercent, (len(TrainingTarget)))

print(ValDataAct.shape)
print(ValData_Concat.shape)
print(ValData_Subtract.shape)


TestDataAct = np.array(GenerateValTargetVector(RawTarget,TestPercent, (len(TrainingTarget)+len(ValDataAct))))
TestData_Concat = GenerateValData(RawData_Concat,TestPercent, (len(TrainingTarget)+len(ValDataAct)))
TestData_Subtract = GenerateValData(RawData_Subtract,TestPercent, (len(TrainingTarget)+len(ValDataAct)))

print(TestDataAct.shape)
print(TestData_Concat.shape)
print(TestData_Subtract.shape)

C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: 'U' mode is deprecated
  after removing the cwd from sys.path.
C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: 'U' mode is deprecated
  from ipykernel import kernelapp as app

(160000,)
(200, 160000)
(100, 160000)
(19999,)
(200, 19999)
(100, 19999)
(19999,)
(200, 19999)
(100, 19999)

# Logistic Regression on GSC Concatenated Features

In [42]:
model = LogisticRegression(lr=0.1, num_iter=300)

X = TrainingData_Concat
y = TrainingTarget
model.fit(X,y)

V = ValData_Concat
y_v = ValDataAct 
T = TestData_Concat
y_t = TestDataAct
preds = model.predict(X)
preds_v = model.predict(V)
preds_t = model.predict(T)

print('--------LOGISTIC REGRESSION ON GSC OBSERVED DATASET---------------')
print('--------------------------FEATURE CONCATENATION-----------------------')
print('prediction accuracy of Training set:'+ str((preds == y).mean()))
print('prediction accuracy of Validation set:'+ str((preds_v == y_v).mean()))

print('prediction accuracy of Testing set:'+ str((preds_t == y_t).mean()))

--------LOGISTIC REGRESSION ON GSC OBSERVED DATASET---------------
--------------------------FEATURE CONCATENATION-----------------------
prediction accuracy of Training set:0.70881875
prediction accuracy of Validation set:0.6896344817240863
prediction accuracy of Testing set:0.6764338216910846

# Logistic Regression on GSC Subtracted Features

In [41]:
model = LogisticRegression(lr=0.1, num_iter=300)

X = TrainingData_Subtract
y = TrainingTarget
model.fit(X,y)

V = ValData_Subtract
y_v = ValDataAct 
T = TestData_Subtract
y_t = TestDataAct
preds = model.predict(X)
preds_v = model.predict(V)
preds_t = model.predict(T)

print('--------LOGISTIC REGRESSION ON GSC OBSERVED DATASET---------------')
print('--------------------------FEATURE SUBTRACTION-----------------------')
print('prediction accuracy of Training set:'+ str((preds == y).mean()))
print('prediction accuracy of Validation set:'+ str((preds_v == y_v).mean()))

print('prediction accuracy of Testing set:'+ str((preds_t == y_t).mean()))

--------LOGISTIC REGRESSION ON GSC OBSERVED DATASET---------------
--------------------------FEATURE SUBTRACTION-----------------------
prediction accuracy of Training set:0.6110875
prediction accuracy of Validation set:0.6834841742087104
prediction accuracy of Testing set:0.6812840642032102

# Neural Network

In [27]:
RawTarget = GetTargetVector('same_diff_pairs_t.csv')
RawData_Concat   = GenerateRawData('Same_Diff_Feature_Concat_withoutlabel.csv',IsSynthetic)
RawData_Subtract   = GenerateRawData('Same_Diff_Feature_Subtract_withoutlabel.csv',IsSynthetic)

TrainingTarget = np.array(GenerateTrainingTarget(RawTarget,TrainingPercent))
TrainingData_Concat   = GenerateTrainingDataMatrix(RawData_Concat,TrainingPercent)
TrainingData_Subtract   = GenerateTrainingDataMatrix(RawData_Subtract,TrainingPercent)

print(TrainingTarget.shape)
print(TrainingData_Concat.shape)
print(TrainingData_Subtract.shape)

ValDataAct = np.array(GenerateValTargetVector(RawTarget,ValidationPercent, (len(TrainingTarget))))
ValData_Concat    = GenerateValData(RawData_Concat,ValidationPercent, (len(TrainingTarget)))
ValData_Subtract    = GenerateValData(RawData_Subtract,ValidationPercent, (len(TrainingTarget)))

print(ValDataAct.shape)
print(ValData_Concat.shape)
print(ValData_Subtract.shape)

TestDataAct = np.array(GenerateValTargetVector(RawTarget,TestPercent, (len(TrainingTarget)+len(ValDataAct))))
TestData_Concat = GenerateValData(RawData_Concat,TestPercent, (len(TrainingTarget)+len(ValDataAct)))
TestData_Subtract = GenerateValData(RawData_Subtract,TestPercent, (len(TrainingTarget)+len(ValDataAct)))

print(TestDataAct.shape)
print(TestData_Concat.shape)
print(TestData_Subtract.shape)

C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: 'U' mode is deprecated
  after removing the cwd from sys.path.
C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: 'U' mode is deprecated
  from ipykernel import kernelapp as app

(235059,)
(18, 235059)
(9, 235059)
(29382,)
(18, 29382)
(9, 29382)
(29381,)
(18, 29381)
(9, 29381)

In [28]:
#Reference: https://enlight.nyc/projects/neural-network/
import numpy as np
TrainingData_Subtract = TrainingData_Subtract[:,:1000]
TrainingData_Subtract = (TrainingData_Subtract)
TrainingData_Subtract = np.array((TrainingData_Subtract))
X = TrainingData_Subtract
y = TrainingTarget[:1000]

xPredicted = np.array((TestData_Subtract))#np.array(([4, 8]), dtype=float)

# scale units
X = X / np.amax(X, axis=0)  # maximum of X array
xPredicted = xPredicted / np.amax(
    xPredicted,
    axis=0)  # maximum of xPredicted (our input data for the prediction)
y = y / 100  # 


class Neural_Network1(object):
    def __init__(self):
        #parameters
        self.inputSize = 9
        self.outputSize = 1
        self.hiddenSize = 1000

        #weights
        self.W1 = np.random.randn(
            self.inputSize,
            self.hiddenSize)  # weight matrix from input to hidden layer
        self.W2 = np.random.randn(
            self.hiddenSize,
            self.outputSize)  # weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        #print((X.T).shape,self.W1.shape)
        self.z = np.dot(X.T,self.W1)  # dot product of X (input) and first set of weights
        self.z2 = self.sigmoid(self.z)  # activation function
        self.z3 = np.dot(
            self.z2, self.W2
        )  # dot product of hidden layer (z2) and second set of weights
        o = self.sigmoid(self.z3)  # final activation function
        return o

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o):
        # backward propgate through the network
        self.o_error = y - o  # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(
            o)  # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(
            self.W2
        )  # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error * self.sigmoidPrime(
            self.z2)  # applying derivative of sigmoid to z2 error

        self.W1 += X.dot(
            self.z2_delta)  # adjusting first set (input --> hidden) weights
        self.W2 = 0#X.dot(self.z2_delta)#self.z2.dot(self.o_delta)  # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)


NN = Neural_Network1()
for i in range(100):  # trains the NN 1,000 times
   
    if(i == 99):
        # mean sum squared loss
        print('---------Neural Network with Human Observed Features-------------')
        print('---------------------Features Subtracted-------------------------')
        print ("Prediction Loss of Training Set: " + str(np.mean(np.square(y - NN.forward(X)))))  
        #print ("\n")
    NN.train(X, y)

ValData_Subtract = ValData_Subtract[:,:1000]
ValData_Subtract = (ValData_Subtract)
ValData_Subtract = np.array((ValData_Subtract))
X = ValData_Subtract
y = ValDataAct[:1000]

xPredicted = np.array((ValData_Subtract))

# scale units
X = X / np.amax(X, axis=0)  # maximum of X array
xPredicted = xPredicted / np.amax(
    xPredicted,
    axis=0)  # maximum of xPredicted (our input data for the prediction)
y = y / 100  

for i in range(100):  # trains the NN 1,000 times
   
    if(i == 99):
        # mean sum squared loss
       
        print ("Prediction Loss of Validation Set: " + str(np.mean(np.square(y - NN.forward(X)))))  
        
    NN.train(X, y)
    
TestData_Subtract = TestData_Subtract[:,:1000]
TestData_Subtract = (TestData_Subtract)
TestData_Subtract = np.array((TestData_Subtract))
X = TestData_Subtract
y = TestDataAct[:1000]

xPredicted = np.array((TestData_Subtract))

# scale units
X = X / np.amax(X, axis=0)  # maximum of X array
xPredicted = xPredicted / np.amax(
    xPredicted,
    axis=0)  # maximum of xPredicted (our input data for the prediction)
y = y / 100  

for i in range(100):  # trains the NN 1,000 times
   
    if(i == 99):
        # mean sum squared loss
        
        print ("Prediction Loss of Testing Set: " + str(np.mean(np.square(y - NN.forward(X)))))  
        #print ("\n")
    NN.train(X, y)
    


# full tutorial: https://enlight.nyc/neural-network

C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == '':

---------Neural Network with Human Observed Features-------------
---------------------Features Subtracted-------------------------
Prediction Loss of Training Set: 0.24216909999999975
Prediction Loss of Validation Set: 0.25
Prediction Loss of Testing Set: 0.25

In [29]:
class Neural_Network2(object):
    def __init__(self):
        #parameters
        self.inputSize = 18
        self.outputSize = 1
        self.hiddenSize = 1000

        #weights
        self.W1 = np.random.randn(
            self.inputSize,
            self.hiddenSize)  # weight matrix from input to hidden layer
        self.W2 = np.random.randn(
            self.hiddenSize,
            self.outputSize)  # weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        #print((X.T).shape,self.W1.shape)
        self.z = np.dot(X.T,self.W1)  # dot product of X (input) and first set of weights
        self.z2 = self.sigmoid(self.z)  # activation function
        self.z3 = np.dot(
            self.z2, self.W2
        )  # dot product of hidden layer (z2) and second set of weights
        o = self.sigmoid(self.z3)  # final activation function
        return o

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o):
        # backward propgate through the network
        self.o_error = y - o  # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(
            o)  # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(
            self.W2
        )  # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error * self.sigmoidPrime(
            self.z2)  # applying derivative of sigmoid to z2 error

        self.W1 += X.dot(
            self.z2_delta)  # adjusting first set (input --> hidden) weights
        self.W2 = 0#X.dot(self.z2_delta)#self.z2.dot(self.o_delta)  # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)


NN = Neural_Network2()
TrainingData_Concat = TrainingData_Concat[:,:1000]

TrainingData_Concat = np.array((TrainingData_Concat))
X = TrainingData_Concat
y = TrainingTarget[:1000]
Xv = ValData_Concat
yv = ValDataAct[:1000]
Xt = TestData_Concat
yt = TestDataAct[:1000]

xPredicted = np.array((TrainingData_Concat))
xvPredicted = np.array((ValData_Concat))
xtPredicted = np.array((TestData_Concat))

# scale units
X = X / np.amax(X, axis=0)  # maximum of X array
xPredicted = xPredicted / np.amax(
    xPredicted,
    axis=0)  # maximum of xPredicted (our input data for the prediction)
y = y / 100  

Xv = Xv / np.amax(Xv, axis=0)  # maximum of X array
xvPredicted = xvPredicted / np.amax(
    xvPredicted,
    axis=0)  # maximum of xPredicted (our input data for the prediction)
yv = yv / 100  

Xt = Xt / np.amax(Xt, axis=0)  # maximum of X array
xtPredicted = xtPredicted / np.amax(
    xtPredicted,
    axis=0)  # maximum of xPredicted (our input data for the prediction)
yt = yt / 100  

for i in range(100):  # trains the NN 1,00 times
   
    if(i == 99):
        # mean sum squared loss
        print('---------Neural Network with Human Observed Features-------------')
        print('---------------------Features Concatenated-------------------------')
        print ("Prediction Loss of Training Set: " + str(np.mean(np.square(y - NN.forward(X)))))
        print ("Prediction Loss of Validation Set: " + str(np.mean(np.square(yv - NN.forward(Xv)))))
        print ("Prediction Loss of Testing Set: " + str(np.mean(np.square(yt - NN.forward(Xt)))))
        #print ("\n")
    NN.train(X, y)
    NN.train(Xv,yv)
    NN.train(Xt,yt)

---------Neural Network with Human Observed Features-------------
---------------------Features Concatenated-------------------------
Prediction Loss of Training Set: 0.24216909999999975
Prediction Loss of Validation Set: 0.25
Prediction Loss of Testing Set: 0.25

In [23]:
RawTarget = GetTargetVector('gsc_same_diff_pairs_t.csv')
RawData_Concat   = GenerateRawData('GSC_Same_Diff_Feature_Concat_withoutlabel.csv',IsSynthetic)
RawData_Subtract   = GenerateRawData('GSC_Same_Diff_Feature_Subtract_withoutlabel.csv',IsSynthetic)

TrainingTarget = np.array(GenerateTrainingTarget(RawTarget,TrainingPercent))
TrainingData_Concat   = GenerateTrainingDataMatrix(RawData_Concat,TrainingPercent)
TrainingData_Subtract   = GenerateTrainingDataMatrix(RawData_Subtract,TrainingPercent)

print(TrainingTarget.shape)
print(TrainingData_Concat.shape)
print(TrainingData_Subtract.shape)

ValDataAct = np.array(GenerateValTargetVector(RawTarget,ValidationPercent, (len(TrainingTarget))))
ValData_Concat    = GenerateValData(RawData_Concat,ValidationPercent, (len(TrainingTarget)))
ValData_Subtract    = GenerateValData(RawData_Subtract,ValidationPercent, (len(TrainingTarget)))

print(ValDataAct.shape)
print(ValData_Concat.shape)
print(ValData_Subtract.shape)


TestDataAct = np.array(GenerateValTargetVector(RawTarget,TestPercent, (len(TrainingTarget)+len(ValDataAct))))
TestData_Concat = GenerateValData(RawData_Concat,TestPercent, (len(TrainingTarget)+len(ValDataAct)))
TestData_Subtract = GenerateValData(RawData_Subtract,TestPercent, (len(TrainingTarget)+len(ValDataAct)))

print(TestDataAct.shape)
print(TestData_Concat.shape)
print(TestData_Subtract.shape)

C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: 'U' mode is deprecated
  after removing the cwd from sys.path.
C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: 'U' mode is deprecated
  from ipykernel import kernelapp as app

(160000,)
(200, 160000)
(100, 160000)
(19999,)
(200, 19999)
(100, 19999)
(19999,)
(200, 19999)
(100, 19999)

In [25]:
class Neural_Network3(object):
    def __init__(self):
        #parameters
        self.inputSize = 200
        self.outputSize = 1
        self.hiddenSize = 1000

        #weights
        self.W1 = np.random.randn(
            self.inputSize,
            self.hiddenSize)  # weight matrix from input to hidden layer
        self.W2 = np.random.randn(
            self.hiddenSize,
            self.outputSize)  # weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        #print((X.T).shape,self.W1.shape)
        self.z = np.dot(X.T,self.W1)  # dot product of X (input) and first set of weights
        self.z2 = self.sigmoid(self.z)  # activation function
        self.z3 = np.dot(
            self.z2, self.W2
        )  # dot product of hidden layer (z2) and second set of weights
        o = self.sigmoid(self.z3)  # final activation function
        return o

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o):
        # backward propgate through the network
        self.o_error = y - o  # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(
            o)  # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(
            self.W2
        )  # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error * self.sigmoidPrime(
            self.z2)  # applying derivative of sigmoid to z2 error

        self.W1 += X.dot(
            self.z2_delta)  # adjusting first set (input --> hidden) weights
        self.W2 = 0#X.dot(self.z2_delta)#self.z2.dot(self.o_delta)  # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)


NN = Neural_Network3()
TrainingData_Concat = TrainingData_Concat[:,:1000]

TrainingData_Concat = np.array((TrainingData_Concat))
X = TrainingData_Concat
y = TrainingTarget[:1000]
Xv = ValData_Concat
yv = ValDataAct[:1000]
Xt = TestData_Concat
yt = TestDataAct[:1000]

xPredicted = np.array((TrainingData_Concat))
xvPredicted = np.array((ValData_Concat))
xtPredicted = np.array((TestData_Concat))

# scale units
X = X / np.amax(X, axis=0)  # maximum of X array
xPredicted = xPredicted / np.amax(
    xPredicted,
    axis=0)  # maximum of xPredicted (our input data for the prediction)
y = y / 100  

Xv = Xv / np.amax(Xv, axis=0)  # maximum of X array
xvPredicted = xvPredicted / np.amax(
    xvPredicted,
    axis=0)  # maximum of xPredicted (our input data for the prediction)
yv = yv / 100  

Xt = Xt / np.amax(Xt, axis=0)  # maximum of X array
xtPredicted = xtPredicted / np.amax(
    xtPredicted,
    axis=0)  # maximum of xPredicted (our input data for the prediction)
yt = yt / 100  

for i in range(100):  # trains the NN 1,00 times
   
    if(i == 99):
        # mean sum squared loss
        print('---------Neural Network with GSC Observed Features-------------')
        print('---------------------Features Concatenated-------------------------')
        print ("Prediction Loss of Training Set: " + str(np.mean(np.square(y - NN.forward(X)))))
        print ("Prediction Loss of Validation Set: " + str(np.mean(np.square(yv - NN.forward(Xv)))))
        print ("Prediction Loss of Testing Set: " + str(np.mean(np.square(yt - NN.forward(Xt)))))
        #print ("\n")
    NN.train(X, y)
    NN.train(Xv,yv)
    NN.train(Xt,yt)

C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:84: RuntimeWarning: invalid value encountered in true_divide
C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:87: RuntimeWarning: invalid value encountered in true_divide

---------Neural Network with GSC Observed Features-------------
---------------------Features Concatenated-------------------------
Prediction Loss of Training Set: 0.24009999999999918
Prediction Loss of Validation Set: 0.25
Prediction Loss of Testing Set: 0.25

In [26]:
class Neural_Network4(object):
    def __init__(self):
        #parameters
        self.inputSize = 100
        self.outputSize = 1
        self.hiddenSize = 1000

        #weights
        self.W1 = np.random.randn(
            self.inputSize,
            self.hiddenSize)  # weight matrix from input to hidden layer
        self.W2 = np.random.randn(
            self.hiddenSize,
            self.outputSize)  # weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        #print((X.T).shape,self.W1.shape)
        self.z = np.dot(X.T,self.W1)  # dot product of X (input) and first set of weights
        self.z2 = self.sigmoid(self.z)  # activation function
        self.z3 = np.dot(
            self.z2, self.W2
        )  # dot product of hidden layer (z2) and second set of weights
        o = self.sigmoid(self.z3)  # final activation function
        return o

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o):
        # backward propgate through the network
        self.o_error = y - o  # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(
            o)  # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(
            self.W2
        )  # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error * self.sigmoidPrime(
            self.z2)  # applying derivative of sigmoid to z2 error

        self.W1 += X.dot(
            self.z2_delta)  # adjusting first set (input --> hidden) weights
        self.W2 = 0#X.dot(self.z2_delta)#self.z2.dot(self.o_delta)  # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)


NN = Neural_Network4()
TrainingData_Subtract = TrainingData_Subtract[:,:1000]

TrainingData_Subtract = np.array((TrainingData_Subtract))
X = TrainingData_Subtract
y = TrainingTarget[:1000]
Xv = ValData_Subtract
yv = ValDataAct[:1000]
Xt = TestData_Subtract
yt = TestDataAct[:1000]

xPredicted = np.array((TrainingData_Subtract))
xvPredicted = np.array((ValData_Subtract))
xtPredicted = np.array((TestData_Subtract))

# scale units
X = X / np.amax(X, axis=0)  # maximum of X array
xPredicted = xPredicted / np.amax(
    xPredicted,
    axis=0)  # maximum of xPredicted (our input data for the prediction)
y = y / 100  

Xv = Xv / np.amax(Xv, axis=0)  # maximum of X array
xvPredicted = xvPredicted / np.amax(
    xvPredicted,
    axis=0)  # maximum of xPredicted (our input data for the prediction)
yv = yv / 100  

Xt = Xt / np.amax(Xt, axis=0)  # maximum of X array
xtPredicted = xtPredicted / np.amax(
    xtPredicted,
    axis=0)  # maximum of xPredicted (our input data for the prediction)
yt = yt / 100  

for i in range(100):  # trains the NN 1,00 times
   
    if(i == 99):
        # mean sum squared loss
        print('---------Neural Network with GSC Observed Features-------------')
        print('---------------------Features Subtracted-------------------------')
        print ("Prediction Loss of Training Set: " + str(np.mean(np.square(y - NN.forward(X)))))
        print ("Prediction Loss of Validation Set: " + str(np.mean(np.square(yv - NN.forward(Xv)))))
        print ("Prediction Loss of Testing Set: " + str(np.mean(np.square(yt - NN.forward(Xt)))))
        #print ("\n")
    NN.train(X, y)
    NN.train(Xv,yv)
    NN.train(Xt,yt)

C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:78: RuntimeWarning: invalid value encountered in true_divide
C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:81: RuntimeWarning: invalid value encountered in true_divide
C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:84: RuntimeWarning: invalid value encountered in true_divide
C:\Users\riskh\Anaconda3\lib\site-packages\ipykernel_launcher.py:87: RuntimeWarning: invalid value encountered in true_divide

---------Neural Network with GSC Observed Features-------------
---------------------Features Subtracted-------------------------
Prediction Loss of Training Set: 0.24009999999999918
Prediction Loss of Validation Set: 0.25
Prediction Loss of Testing Set: 0.25